version: '3.8'
services:
  
  spark:
    build:
      context: . 
      dockerfile: model/Dockerfile
    hostname: spark
    container_name: spark
    volumes:
      - ./tmp:/tmp  
      - ./model/clustering.py:/home/spark/clustering.py
      - ./model/regressione.py:/home/spark/regressione.py
      - ./model/mod/:/home/spark/model
    command: > 
      /opt/spark/bin/spark-submit --conf spark.driver.extraJavaOptions="-Divy.cache.dir=/tmp -Divy.home=/tmp" --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.2  /home/spark/regressione.py
   

 
 


volumes:
  data_volume:
  spark-logs:
  